version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - covidcast-fe
    depends_on:
      - covidcastdb
      - server

  server:
    container_name: server
    build: ./server
    environment:
      - DB_HOST=covidcastdb
      - DB_PORT=3306
    ports:
      - "8000:5000"
    expose:
        - 8000
    networks:
      - covidcast-be
      - covidcast-fe
    depends_on:
      - covidcastdb

  covidcastdb:
    container_name: covidcastdb
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    command: --max_allowed_packet=250M
    environment:
        MYSQL_ROOT_PASSWORD: test
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: covidcast
    ports:
        - '3306:3306'
    networks:
        - covidcast-be

networks:
    covidcast-be:
        driver: bridge
    covidcast-fe:
        driver: bridge